name: Auto Tag on PR Merge

on:
  pull_request:
    types: [closed]
    branches: [ master ]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Version
        id: version
        run: |
          # Get latest tag or start with v1.0.0
          if git describe --tags --abbrev=0 2>/dev/null; then
            LAST_TAG=$(git describe --tags --abbrev=0)
            # Auto-increment patch version (v1.0.0 → v1.0.1)
            if [[ $LAST_TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              MAJOR=${BASH_REMATCH[1]}
              MINOR=${BASH_REMATCH[2]} 
              PATCH=${BASH_REMATCH[3]}
              NEW_PATCH=$((PATCH + 1))
              NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
            else
              NEW_VERSION="v1.0.0"
            fi
          else
            NEW_VERSION="v1.0.0"
          fi
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}